/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RepositoryIdImport } from './routes/repository/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const RepositoriesIndexLazyImport = createFileRoute('/repositories/')()
const DashboardIndexLazyImport = createFileRoute('/dashboard/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RepositoriesIndexLazyRoute = RepositoriesIndexLazyImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/repositories/index.lazy').then((d) => d.Route),
)

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)

const RepositoryIdRoute = RepositoryIdImport.update({
  id: '/repository/$id',
  path: '/repository/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/repository/$id': {
      id: '/repository/$id'
      path: '/repository/$id'
      fullPath: '/repository/$id'
      preLoaderRoute: typeof RepositoryIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/repository/$id': typeof RepositoryIdRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/repositories': typeof RepositoriesIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/repository/$id': typeof RepositoryIdRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/repositories': typeof RepositoriesIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/repository/$id': typeof RepositoryIdRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/repositories/': typeof RepositoriesIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/repository/$id' | '/dashboard' | '/repositories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repository/$id' | '/dashboard' | '/repositories'
  id: '__root__' | '/' | '/repository/$id' | '/dashboard/' | '/repositories/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RepositoryIdRoute: typeof RepositoryIdRoute
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  RepositoriesIndexLazyRoute: typeof RepositoriesIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RepositoryIdRoute: RepositoryIdRoute,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  RepositoriesIndexLazyRoute: RepositoriesIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/repository/$id",
        "/dashboard/",
        "/repositories/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/repository/$id": {
      "filePath": "repository/$id.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.lazy.tsx"
    },
    "/repositories/": {
      "filePath": "repositories/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
